//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VamsDeviceListener.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.12:9002/")]
        public string BaseAddress {
            get {
                return ((string)(this["BaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://viraatlabs.com/VAMSDeviceIntegration/api/SpeedFace/")]
        public string WebApiUrl {
            get {
                return ((string)(this["WebApiUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BS")]
        public string ListernerFor {
            get {
                return ((string)(this["ListernerFor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3VzZXJkYXRhIjoie1wiY29tcGxleElkXCI6XCIxN1wiLFwidmFsaWRpdHlcIjpcIjE2NTIyNTMyMzkwNDVcIn0iLCJuYmYiOjE2MjA3MTcyMzksImV4cCI6MTY1MjI1MzIzOSwiaWF0IjoxNjIwNzE3MjM5LCJpc3MiOiJodHRwczovL3d3dy52YW1zZ2xvYmFsLmNvbSIsImF1ZCI6Imh0dHBzOi8vd3d3LnZhbXNnbG9iYWwuY29tIn0.C8NWZES5WqWrYYfYHlROTi2NcJBuYmeGWkRNlt-2JuE")]
        public string WebApiToken {
            get {
                return ((string)(this["WebApiToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WriteInfoLog {
            get {
                return ((bool)(this["WriteInfoLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRestAPI {
            get {
                return ((bool)(this["IsRestAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float TmIntervalInMin {
            get {
                return ((float)(this["TmIntervalInMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15:00")]
        public string RestartApplicationTime {
            get {
                return ((string)(this["RestartApplicationTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://vamsglobal.in/VamsCorporateVer270/ws/wsDeviceEvents.asmx")]
        public string VamsDeviceListener_wsEvents_wsDeviceEvents {
            get {
                return ((string)(this["VamsDeviceListener_wsEvents_wsDeviceEvents"]));
            }
        }
    }
}
